sudo: required
services:
  - docker

before_install:
  - docker build -t zcl/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run zcl/react-test npm test -- --coverage
#build with production image
after_success:
  - docker build -t zcl/multi-client ./client
  - docker build -t zcl/multi-nginx ./nginx
  - docker build -t zcl/multi-server ./server
  - docker build -t zcl/multi-worker ./worker

#Log in to the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

# Take those image and push them to the docker hub, changed the password and username 
  - docker push zcl/multi-client
  - docker push zcl/multi-nginx
  - docker push zcl/multi-server
  - docker push zcl/multi-worker


