version: '3.3'
services: 
  nginx:
    restart: always
    build: 
        dockerfile: Dockerfile.dev
        context: ./nginx
    ports: 
      - '3050:80'
  postgres:
    image: 'postgres:latest'
  redis:
    image: 'redis:latest'
  #server api
  api:
    ##
    depends_on:
      - postgres
    build: 
      dockerfile: Dockerfile.dev
      #folder name in local
      context: ./server
    volumes:
      #take off hands of the below folder
      - /app/node_modules
      #anything point to app will direct to ./server(local)
      - ./server:/app
    environment:
      #use the service name
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      #service name
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
    ##
    environment: 
      - REDIS_HOST=redis
      - REDIS_PORT=6379


